kind: Secret
apiVersion: v1
metadata:
  name: my-secrets
type: Opaque

data:
  MYSQL_URI: bXlzcWw6Ly9yb290OmFkbWluQGRiLXN2YzozMzA2L2Rldm9wcw==
  MYSQL_HOST: ZGItc3Zj
  MYSQL_PASSWORD: YWRtaW4=
  MYSQL_USER: cm9vdA==
  MYSQL_DB: ZGV2b3Bz
