name: Push and Deploy to GKE

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: 'my-flask-app'
  PROJECT_ID: 'project-3d4fd68e-9492-4690-aa8'
  AR_REPO_LOCATION: 'asia-south1'
  AR_URL: asia-south1-docker.pkg.dev/project-3d4fd68e-9492-4690-aa8/my-registry
  SERVICE_ACCOUNT: cluster-gke@project-3d4fd68e-9492-4690-aa8.iam.gserviceaccount.com
  WORKLOAD_IDENTITY_PROVIDER: projects/511846968460/locations/global/workloadIdentityPools/github-pool-gke/providers/github
  
  # GKE specific variables
  GKE_CLUSTER: 'cluster-1'       # Apne GKE cluster ka naam yahan likhein
  GKE_ZONE: 'asia-south1'           # Cluster ka zone ya region (e.g., us-central1-a)
  DEPLOYMENT_NAME: 'two-tier-app' # Kubernetes deployment name
  CONTAINER_NAME: 'two-tier-app'           # Container name inside the deployment

jobs:
  build-and-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # 1. Google Authentication
    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        project_id: ${{ env.PROJECT_ID }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

    # 2. Docker Registry Login
    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v3'
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        registry: '${{ env.AR_REPO_LOCATION }}-docker.pkg.dev'

    # 3. Build & Push Image to Artifact Registry
    - name: Build and Push Container
      run: |-
        docker build -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" ./
        docker push "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

    # 4. Get GKE Credentials (kubectl setup)
    - name: Set up GKE credentials
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # 5. Deploy / Update Image on GKE Cluster
    - name: Deploy to GKE
      run: |-
        # Existing deployment ki image update karein
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.CONTAINER_NAME }}=${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        
        # Rollout status verify karein
        kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}
