name: Build and Deploy to GKEs

on:
  push:
   branches:
     - main

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: project-3d4fd68e-9492-4690-aa8
  REGION: asia-south1
  REPOSITORY: image-collector
  IMAGE_NAME: app
  CLUSTER_NAME: cluster-1
  NAMESPAE: app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: sonarqube scan
        uses: SonarSource/sonarqube-scan-action@v8
        with:
          args: >
            -Dsonar.projectKey=my-app
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: squ_06458f17b2557bc5723c03d2064c018e87c0e845
          SONAR_HOST_URL: http://34.123.118.124:9000

      - name: Authentication to GCP
        uses: google-github-actions/auth@v2
        with:
          workload-identity-provider: projects/511846968460/locations/global/workloadIdentityPools/identity-pool/providers/github
          service-account: image-pusher@project-3d4fd68e-9492-4690-aa8.iam.gserviceaccount.com

      - name: gcloud SDK setup
        uses: google-github-actions/setup-gcloud@v2

      - name: configure docker to Artifact
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Building image
        run: |
          docker build \
            -t asia-south1-docker.pkg.dev/project-3d4fd68e-9492-4690-aa8/image-collector/app:${{ github.sha }} ./

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: asia-south1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA}
          format: table
          exit-code: 0
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: pushing image to Artifact
        run: |
          docke push \
            asia-south1-docker.pkg.dev/project-3d4fd68e-9492-4690-aa8/image-collector/app:${{ github.sha }}

      - name: get GKE credentials
        run: |
           gcloud container clusters get-credentials ${CLUSTER_NAME} \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }}

      - name: Deploy to GKE cluster
        run: |
          kubectl set image deployment/app-deploy \
            app-cont=europe-north2-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA} \
            -n ${NAMESPACE}

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/app-deploy \
            -n ${NAMESPACE} \
            --timeout=5m
          
            
    
  

